create table DEFT_STEPEX (
REQ2STEP_ID NUMBER(12) PRIMARY KEY,
REQID NUMBER(12),
STEP_ID  NUMBER(12),
STATUS VARCHAR2(16),
PRIORITY NUMBER(5),
DEF_TIME DATE,
APPR_TIME DATE,
EXE_TIME DATE,
DONE_TIME DATE,
INPUT_EVENTS NUMBER(8),
OUTPUT_EVENTS NUMBER(8)
)
